#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jna
Version  : 3.4.0
Release  : 1
URL      : https://github.com/java-native-access/jna/archive/3.4.0.tar.gz
Source0  : https://github.com/java-native-access/jna/archive/3.4.0.tar.gz
Source1  : https://repo1.maven.org/maven2/net/java/dev/jna/jna/3.4.0/jna-3.4.0.pom
Source2  : https://repo1.maven.org/maven2/net/java/dev/jna/jna/3.5.2/jna-3.5.2.jar
Source3  : https://repo1.maven.org/maven2/net/java/dev/jna/jna/3.5.2/jna-3.5.2.pom
Source4  : https://repo1.maven.org/maven2/net/java/dev/jna/platform/3.4.0/platform-3.4.0.pom
Source5  : https://repo1.maven.org/maven2/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar
Source6  : https://repo1.maven.org/maven2/net/java/dev/jna/platform/3.5.2/platform-3.5.2.pom
Summary  : Library supporting Foreign Function Interfaces
Group    : Development/Tools
License  : LGPL-2.1 MIT
Requires: mvn-jna-data = %{version}-%{release}

%description
Status
======
libffi-3.0.10 was released on XXXXXXXXXX, 2011. Check the libffi web
page for updates: <URL:http://sourceware.org/libffi/>.

%package data
Summary: data components for the mvn-jna package.
Group: Data

%description data
data components for the mvn-jna package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.4.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.4.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.5.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.5.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.4.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.4.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.5.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.5.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.5.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.5.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.4.0/jna-3.4.0.pom
/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.5.2/jna-3.5.2.jar
/usr/share/java/.m2/repository/net/java/dev/jna/jna/3.5.2/jna-3.5.2.pom
/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.4.0/platform-3.4.0.pom
/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.jar
/usr/share/java/.m2/repository/net/java/dev/jna/platform/3.5.2/platform-3.5.2.pom
